// packages/vue/Breadcrumb.vue
<template>
  <nav class="breadcrumb" aria-label="Breadcrumb">
    <template v-for="(item, index) in items" :key="index">
      <span v-if="index > 0" class="breadcrumb-separator" aria-hidden="true">
        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">
          <polyline points="9 18 15 12 9 6" />
        </svg>
      </span>
      <a v-if="item.href && index < items.length - 1" :href="item.href" class="breadcrumb-item">
        {{ item.label }}
      </a>
      <span
        v-else
        class="breadcrumb-item" :data-state="index === items.length - 1 ? 'active' : undefined"
        :aria-current="index === items.length - 1 ? 'page' : undefined"
      >
        {{ item.label }}
      </span>
    </template>
  </nav>
</template>

<script setup lang="ts">
interface BreadcrumbItem {
  label: string;
  href?: string;
}

interface Props {
  items: BreadcrumbItem[];
}

defineProps<Props>();
</script>

// test-native/.mocha-web-temp/src/app/mocha-ds/breadcrumb.component.ts
import { Component, input } from '@angular/core';

export interface BreadcrumbItem {
  label: string;
  href?: string;
}

@Component({
  selector: 'breadcrumb',
  standalone: true,
  template: `
    <nav class="breadcrumb" aria-label="Breadcrumb">
      @for (item of items(); track $index) {
        @if (!$first) {
          <span class="breadcrumb-separator" aria-hidden="true">
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
              <polyline points="9 18 15 12 9 6"/>
            </svg>
          </span>
        }
        @if (item.href && !$last) {
          <a [href]="item.href" class="breadcrumb-item">{{ item.label }}</a>
        } @else {
          <span
            class="breadcrumb-item{{ $last ? ' breadcrumb-item--active' : '' }}"
            [attr.aria-current]="$last ? 'page' : undefined"
          >
            {{ item.label }}
          </span>
        }
      }
    </nav>
  `
})
export class BreadcrumbComponent {
  items = input<BreadcrumbItem[]>([]);
}
