// packages/vue/Tile.vue
<template>
  <div :class="tileClass" v-bind="$attrs">
    <slot>
      <div v-if="$slots.icon || icon" class="tile-icon">
        <slot name="icon">{{ icon }}</slot>
      </div>

      <div v-if="$slots.content || title || subtitle" class="tile-content">
        <slot name="content">
          <span v-if="title" class="tile-title">{{ title }}</span>
          <span v-if="subtitle" class="tile-subtitle">{{ subtitle }}</span>
        </slot>
      </div>

      <div v-if="$slots.meta || meta" class="tile-meta">
        <slot name="meta">{{ meta }}</slot>
      </div>
    </slot>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';

type TileVariant = 'flat' | 'elevated' | 'outline' | 'tonal' | 'colored';
type TileSize = 'sm' | 'md' | 'lg';
type TileShape = 'square' | 'rounded' | 'pill';
type TileOrientation = 'horizontal' | 'vertical' | 'vertical-center';
type TileIndicator = 'none' | 'top' | 'bottom' | 'left' | 'right';
type TileColor =
  | 'rosewater'
  | 'flamingo'
  | 'pink'
  | 'mauve'
  | 'red'
  | 'maroon'
  | 'peach'
  | 'yellow'
  | 'green'
  | 'teal'
  | 'sky'
  | 'sapphire'
  | 'blue'
  | 'lavender';

interface Props {
  variant?: TileVariant;
  size?: TileSize;
  shape?: TileShape;
  orientation?: TileOrientation;
  color?: TileColor;
  indicator?: TileIndicator;
  isInteractive?: boolean;
  isSelected?: boolean;
  isDisabled?: boolean;
  icon?: any;
  title?: string;
  subtitle?: string;
  meta?: string;
}

const props = withDefaults(defineProps<Props>(), {
  variant: 'flat',
  size: 'md',
  shape: 'rounded',
  orientation: 'horizontal',
  color: 'mauve',
  indicator: 'none',
  isInteractive: false,
  isSelected: false,
  isDisabled: false,
});

const tileClass = computed(() => {
  return [
    'tile',
    `tile--${props.variant}`,
    `tile--${props.size}`,
    `tile--${props.shape}`,
    `tile--${props.orientation}`,
    props.color ? `tile--${props.color}` : '',
    props.indicator !== 'none' ? `tile--indicator-${props.indicator}` : '',
    props.isInteractive ? 'tile--interactive' : '',
    props.isSelected ? 'tile--selected' : '',
    props.isDisabled ? 'tile--disabled' : '',
  ];
});
</script>

// test-native/.mocha-web-temp/src/app/mocha-ds/tile.component.ts
import { Component, input, computed } from '@angular/core';

export type TileVariant = 'flat' | 'elevated' | 'outline' | 'tonal' | 'colored';
export type TileSize = 'sm' | 'md' | 'lg';
export type TileShape = 'square' | 'rounded' | 'pill';
export type TileOrientation = 'horizontal' | 'vertical' | 'vertical-center';
export type TileIndicator = 'none' | 'top' | 'bottom' | 'left' | 'right';
export type TileColor =
  | 'rosewater'
  | 'flamingo'
  | 'pink'
  | 'mauve'
  | 'red'
  | 'maroon'
  | 'peach'
  | 'yellow'
  | 'green'
  | 'teal'
  | 'sky'
  | 'sapphire'
  | 'blue'
  | 'lavender';

@Component({
  selector: 'tile',
  standalone: true,
  template: `
    <div [class]="tileClass()">
      <ng-content>
        @if (hasIcon()) {
          <div class="tile-icon">
            <ng-content select="[icon]"></ng-content>
          </div>
        }
        @if (title() || subtitle() || hasContent()) {
          <div class="tile-content">
            @if (title()) {
              <span class="tile-title">{{ title() }}</span>
            }
            @if (subtitle()) {
              <span class="tile-subtitle">{{ subtitle() }}</span>
            }
            <ng-content select="[content]"></ng-content>
          </div>
        }
        @if (hasMeta()) {
          <div class="tile-meta">
            <ng-content select="[meta]"></ng-content>
          </div>
        }
      </ng-content>
    </div>
  `
})
export class TileComponent {
  variant = input<TileVariant>('flat');
  size = input<TileSize>('md');
  shape = input<TileShape>('rounded');
  orientation = input<TileOrientation>('horizontal');
  color = input<TileColor>('mauve');
  indicator = input<TileIndicator>('none');
  isInteractive = input<boolean>(false);
  isSelected = input<boolean>(false);
  isDisabled = input<boolean>(false);

  title = input<string | undefined>(undefined);
  subtitle = input<string | undefined>(undefined);

  hasIcon = input<boolean>(false);
  hasContent = input<boolean>(false);
  hasMeta = input<boolean>(false);

  tileClass = computed(() => {
    return [
      'tile',
      `tile--${this.variant()}`,
      `tile--${this.size()}`,
      `tile--${this.shape()}`,
      `tile--${this.orientation()}`,
      this.color() ? `tile--${this.color()}` : '',
      this.indicator() !== 'none' ? `tile--indicator-${this.indicator()}` : '',
      this.isInteractive() ? 'tile--interactive' : '',
      this.isSelected() ? 'tile--selected' : '',
      this.isDisabled() ? 'tile--disabled' : ''
    ].filter(Boolean).join(' ');
  });
}
