// test-native/.mocha-web-temp/src/app/mocha-ds/button.component.ts
import {
  Component,
  input,
  computed,
  output,
  inject,
  ElementRef,
  AfterViewInit,
  OnDestroy,
  Optional
} from '@angular/core';
import { ButtonGroupComponent } from './button-group.component';

export type ButtonVariant = 'filled' | 'tonal' | 'outline' | 'ghost';
export type ButtonColor =
  | 'rosewater'
  | 'flamingo'
  | 'pink'
  | 'mauve'
  | 'red'
  | 'maroon'
  | 'peach'
  | 'yellow'
  | 'green'
  | 'teal'
  | 'sky'
  | 'sapphire'
  | 'blue'
  | 'lavender';
export type ButtonSize = 'sm' | 'md' | 'lg';
export type ButtonShape = 'square' | 'rounded' | 'pill';

@Component({
  selector: 'button[btn]',
  standalone: true,
  host: {
    '[attr.data-variant]': 'variant()',
    '[attr.data-color]': 'color()',
    '[attr.data-size]': 'size()',
    '[attr.data-shape]': 'shape()',
    '[attr.data-state]': 'resolvedState()',
    '[class.btn]': 'true',
    '[disabled]': 'isDisabled()',
    '[attr.role]': 'isGroupSingle() ? "radio" : null',
    '[attr.aria-checked]': 'isGroupSingle() ? isActive() : null',
    '[attr.tabindex]': 'isGroupSingle() ? (isActive() ? 0 : -1) : 0',
  },
  template: `
    <span class="btn-content">
      @if (isLoading()) {
        <span class="btn-spinner" aria-hidden="true"></span>
      }
      <span class="btn-icon-left" style="display: inline-flex; align-items: center">
        <ng-content select="[leftIcon]"></ng-content>
      </span>
      <ng-content></ng-content>
      <span class="btn-icon-right" style="display: inline-flex; align-items: center">
        <ng-content select="[rightIcon]"></ng-content>
      </span>
    </span>
  `
})
export class ButtonComponent implements AfterViewInit, OnDestroy {
  variant = input<ButtonVariant>('filled');
  color = input<ButtonColor>('mauve');
  size = input<ButtonSize>('md');
  shape = input<ButtonShape>('rounded');
  isLoading = input<boolean>(false);
  leftIcon = input<string>('');
  rightIcon = input<string>('');
  value = input<any>(undefined);
  disabled = input<boolean>(false);

  click = output<MouseEvent>();

  private buttonGroup = inject(ButtonGroupComponent, { optional: true });
  private el = inject(ElementRef);

  isGroupSingle = computed((): boolean => {
    return this.buttonGroup ? this.buttonGroup.selectionMode() === 'single' : false;
  });

  isGroupDisabled = computed((): boolean => {
    return this.buttonGroup ? this.buttonGroup.disabled() : false;
  });

  isDisabled = computed((): boolean => {
    return this.disabled() || this.isGroupDisabled() || this.isLoading();
  });

  isActive = computed((): boolean => {
    if (!this.buttonGroup || this.value() === null || this.value() === undefined) return false;
    return this.buttonGroup.isButtonActive(this.value());
  });

  resolvedState = computed((): string | undefined => {
    if (this.isLoading()) return 'loading';
    if (this.isActive()) return 'active';
    return undefined;
  });

  handleClick(event: MouseEvent): void {
    if (this.buttonGroup && this.value() !== null && this.value() !== undefined) {
      this.buttonGroup.selectButton(this.value());
    }
    this.click.emit(event);
  }

  ngAfterViewInit() {
    if (this.buttonGroup && this.value() !== null && this.value() !== undefined) {
      this.buttonGroup.registerButton(this.value(), this.el.nativeElement);
    }
  }

  ngOnDestroy() {
    if (this.buttonGroup && this.value() !== null && this.value() !== undefined) {
      this.buttonGroup.unregisterButton(this.value());
    }
  }
}

// packages/vue/Button.vue
<template>
  <button
    ref="buttonEl"
    :class="buttonClass"
    :disabled="disabled || groupDisabled || isLoading"
    :role="groupSelectionMode === 'single' ? 'radio' : undefined"
    :aria-checked="groupSelectionMode === 'single' ? isActive : undefined"
    :tabindex="groupSelectionMode === 'single' ? (isActive ? 0 : -1) : 0"
    :data-variant="variant"
    :data-color="color"
    :data-size="size"
    :data-shape="shape"
    :data-state="isLoading ? 'loading' : (isActive ? 'active' : undefined)"
    @click="handleClick"
    v-bind="$attrs"
  >
    <span class="btn-content">
      <span v-if="isLoading" class="btn-spinner" aria-hidden="true"></span>
      <span v-else-if="$slots.leftIcon" class="btn-icon-left" style="display: inline-flex; align-items: center">
        <slot name="leftIcon" />
      </span>
      <slot />
      <span v-if="!isLoading && $slots.rightIcon" class="btn-icon-right" style="display: inline-flex; align-items: center">
        <slot name="rightIcon" />
      </span>
    </span>
  </button>
</template>

<script setup lang="ts">
import { computed, inject, ref, onMounted, onUnmounted, watch } from 'vue';

type ButtonVariant = 'filled' | 'tonal' | 'outline' | 'ghost';
type ButtonColor =
  | 'rosewater'
  | 'flamingo'
  | 'pink'
  | 'mauve'
  | 'red'
  | 'maroon'
  | 'peach'
  | 'yellow'
  | 'green'
  | 'teal'
  | 'sky'
  | 'sapphire'
  | 'blue'
  | 'lavender';
type ButtonSize = 'sm' | 'md' | 'lg';
type ButtonShape = 'square' | 'rounded' | 'pill';

interface Props {
  variant?: ButtonVariant;
  color?: ButtonColor;
  size?: ButtonSize;
  shape?: ButtonShape;
  isLoading?: boolean;
  disabled?: boolean;
  value?: any;
}

const props = withDefaults(defineProps<Props>(), {
  variant: 'filled',
  color: 'mauve',
  size: 'md',
  shape: 'rounded',
  isLoading: false,
  disabled: false,
});

const emit = defineEmits<{
  (e: 'click', event: MouseEvent): void;
}>();

const buttonEl = ref<HTMLElement | null>(null);

// Inject group context for radio/multi selection
const groupSelectionMode = inject<any>('buttonGroupSelectionMode', null);
const groupValue = inject<any>('buttonGroupValue', null);
const groupDisabled = inject<any>('buttonGroupDisabled', false);
const groupSelect = inject<any>('buttonGroupSelect', null);
const registerButton = inject<any>('registerButton', null);
const unregisterButton = inject<any>('unregisterButton', null);

const isActive = computed(() => {
  if (!groupSelectionMode || !groupSelectionMode.value || props.value === undefined) {
    return false;
  }
  if (groupSelectionMode.value === 'single') {
    return groupValue.value === props.value;
  }
  if (groupSelectionMode.value === 'multiple') {
    return Array.isArray(groupValue.value) && groupValue.value.includes(props.value);
  }
  return false;
});

onMounted(() => {
  if (registerButton && props.value !== undefined && buttonEl.value) {
    registerButton(props.value, buttonEl.value);
  }
});

watch(() => props.value, (newVal, oldVal) => {
  if (unregisterButton && oldVal !== undefined) {
    unregisterButton(oldVal);
  }
  if (registerButton && newVal !== undefined && buttonEl.value) {
    registerButton(newVal, buttonEl.value);
  }
});

onUnmounted(() => {
  if (unregisterButton && props.value !== undefined) {
    unregisterButton(props.value);
  }
});

const buttonClass = computed(() => {
  return 'btn';
});

function handleClick(event: MouseEvent) {
  if (groupSelect && props.value !== undefined) {
    groupSelect(props.value);
  }
  emit('click', event);
}
</script>
