// packages/angular/card.component.ts
import { Component, input, computed } from '@angular/core';

export type CardVariant = 'filled' | 'elevated' | 'outline' | 'flat' | 'colored';
export type CardShape = 'square' | 'rounded' | 'pill';
export type CardPadding = 'none' | 'sm' | 'md' | 'lg';
export type CardAccentColor =
  | 'rosewater'
  | 'flamingo'
  | 'pink'
  | 'mauve'
  | 'red'
  | 'maroon'
  | 'peach'
  | 'yellow'
  | 'green'
  | 'teal'
  | 'sky'
  | 'sapphire'
  | 'blue'
  | 'lavender';
export type CardAccentPosition = 'top' | 'left' | 'none';

@Component({
  selector: 'card',
  standalone: true,
  template: `
    <div
      [class]="cardClass()"
      [attr.data-variant]="variant()"
      [attr.data-shape]="shape()"
      [attr.data-padding]="padding()"
      [attr.data-color]="accentColor() || null"
      [attr.data-accent]="accentColor() && accentPosition() !== 'none' ? accentPosition() : null"
      [attr.data-interactive]="isInteractive() ? 'true' : null"
    >
      <ng-content></ng-content>
    </div>
  `
})
export class CardComponent {
  variant = input<CardVariant>('filled');
  shape = input<CardShape>('rounded');
  padding = input<CardPadding>('md');
  accentColor = input<CardAccentColor | undefined>(undefined);
  accentPosition = input<CardAccentPosition>('none');
  isInteractive = input<boolean>(false);

  cardClass = computed(() => {
    return 'card';
  });
}

@Component({
  selector: 'card-header',
  standalone: true,
  template: `
    <div class="card-header">
      @if (hasAvatar()) {
        <div class="card-avatar">
          <ng-content select="[avatar]"></ng-content>
        </div>
      }
      <div class="card-header-content">
        @if (title()) {
          <h3 class="card-title">{{ title() }}</h3>
        }
        @if (subtitle()) {
          <p class="card-subtitle">{{ subtitle() }}</p>
        }
        <ng-content select="[header-content]"></ng-content>
      </div>
      <div class="card-actions">
        <ng-content select="[actions]"></ng-content>
      </div>
      <ng-content></ng-content>
    </div>
  `
})
export class CardHeaderComponent {
  title = input<string | undefined>(undefined);
  subtitle = input<string | undefined>(undefined);
  hasAvatar = input<boolean>(false);
}

@Component({
  selector: 'card-body',
  standalone: true,
  template: `
    <div class="card-body">
      <ng-content></ng-content>
    </div>
  `
})
export class CardBodyComponent {}

@Component({
  selector: 'card-footer',
  standalone: true,
  template: `
    <div class="card-footer">
      <ng-content></ng-content>
    </div>
  `
})
export class CardFooterComponent {}

@Component({
  selector: 'card-media',
  standalone: true,
  template: `
    <div class="card-media">
      @if (src()) {
        <img [src]="src()" [alt]="alt()" />
      } @else {
        <ng-content></ng-content>
      }
    </div>
  `
})
export class CardMediaComponent {
  src = input<string | undefined>(undefined);
  alt = input<string>('');
}

// packages/vue/Card.vue
<template>
  <div
    :class="cardClass"
    :data-variant="variant"
    :data-shape="shape"
    :data-padding="padding"
    :data-color="accentColor"
    :data-accent="accentColor && accentPosition !== 'none' ? accentPosition : undefined"
    :data-interactive="isInteractive ? 'true' : undefined"
    v-bind="$attrs"
  >
    <!-- Header Slot / Element -->
    <div v-if="$slots.header || title || subtitle || $slots.avatar || $slots.actions" class="card-header">
      <div v-if="$slots.avatar" class="card-avatar">
        <slot name="avatar" />
      </div>
      <div v-if="title || subtitle || $slots.header" class="card-header-content">
        <slot name="header">
          <h3 v-if="title" class="card-title">{{ title }}</h3>
          <p v-if="subtitle" class="card-subtitle">{{ subtitle }}</p>
        </slot>
      </div>
      <div v-if="$slots.actions" class="card-actions">
        <slot name="actions" />
      </div>
    </div>

    <!-- Media Slot / Element -->
    <div v-if="$slots.media || mediaSrc" class="card-media">
      <slot name="media">
        <img :src="mediaSrc" :alt="mediaAlt" />
      </slot>
    </div>

    <!-- Body Slot / Element -->
    <div class="card-body">
      <slot />
    </div>

    <!-- Footer Slot / Element -->
    <div v-if="$slots.footer" class="card-footer">
      <slot name="footer" />
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';

type CardVariant = 'filled' | 'elevated' | 'outline' | 'flat' | 'colored';
type CardShape = 'square' | 'rounded' | 'pill';
type CardPadding = 'none' | 'sm' | 'md' | 'lg';
type CardAccentColor =
  | 'rosewater'
  | 'flamingo'
  | 'pink'
  | 'mauve'
  | 'red'
  | 'maroon'
  | 'peach'
  | 'yellow'
  | 'green'
  | 'teal'
  | 'sky'
  | 'sapphire'
  | 'blue'
  | 'lavender';
type CardAccentPosition = 'top' | 'left' | 'none';

interface Props {
  variant?: CardVariant;
  shape?: CardShape;
  padding?: CardPadding;
  accentColor?: CardAccentColor;
  accentPosition?: CardAccentPosition;
  isInteractive?: boolean;
  title?: string;
  subtitle?: string;
  mediaSrc?: string;
  mediaAlt?: string;
}

const props = withDefaults(defineProps<Props>(), {
  variant: 'filled',
  shape: 'rounded',
  padding: 'md',
  accentPosition: 'none',
  isInteractive: false,
  mediaAlt: '',
});

const cardClass = computed(() => {
  return 'card';
});
</script>
