// test-native/.mocha-web-temp/src/app/mocha-ds/overlay.component.ts
import { Component, input, output, OnDestroy, ElementRef, ViewChild, effect } from '@angular/core';

let activeOverlayCount = 0;

@Component({
  selector: 'overlay',
  standalone: true,
  template: `
    @if (shouldRender) {
      <div
        #overlayElement
        class="overlay"
        [attr.data-state]="isAnimatedIn ? 'open' : null"
        [attr.data-placement]="placement()"
        [style.zIndex]="zIndex"
        (click)="handleOverlayClick($event)"
        role="presentation"
      >
        <ng-content></ng-content>
      </div>
    }
  `
})
export class OverlayComponent implements OnDestroy {
  isOpen = input<boolean>(false);
  closeOnOverlayClick = input<boolean>(true);
  closeOnEsc = input<boolean>(true);
  placement = input<string>('');

  close = output<void>();

  @ViewChild('overlayElement') overlayElement!: ElementRef;

  shouldRender = false;
  isAnimatedIn = false;
  zIndex = 1000;
  private timeoutId: any = null;

  constructor() {
    effect(() => {
      const open = this.isOpen();
      clearTimeout(this.timeoutId);
      if (open) {
        activeOverlayCount++;
        this.zIndex = 1000 + activeOverlayCount;
        this.shouldRender = true;
        document.body.style.overflow = 'hidden';

        this.timeoutId = setTimeout(() => {
          this.isAnimatedIn = true;
        }, 10);

        window.addEventListener('keydown', this.handleKeyDown);
      } else {
        this.isAnimatedIn = false;
        window.removeEventListener('keydown', this.handleKeyDown);

        this.timeoutId = setTimeout(() => {
          this.shouldRender = false;
          if (activeOverlayCount > 0) {
            activeOverlayCount--;
          }
          if (activeOverlayCount === 0) {
            document.body.style.overflow = '';
          }
        }, 200);
      }
    });
  }

  ngOnDestroy(): void {
    clearTimeout(this.timeoutId);
    window.removeEventListener('keydown', this.handleKeyDown);
    if (this.isOpen()) {
      if (activeOverlayCount > 0) {
        activeOverlayCount--;
      }
      if (activeOverlayCount === 0) {
        document.body.style.overflow = '';
      }
    }
  }

  handleOverlayClick(event: MouseEvent): void {
    if (this.closeOnOverlayClick() && event.target === this.overlayElement.nativeElement) {
      this.close.emit();
    }
  }

  private handleKeyDown = (event: KeyboardEvent): void => {
    if (event.key === 'Escape' && this.isOpen() && this.closeOnEsc()) {
      if (this.zIndex === 1000 + activeOverlayCount) {
        this.close.emit();
      }
    }
  };
}

// packages/vue/Overlay.vue
<template>
  <Teleport to="body">
    <div
      v-if="shouldRender"
      class="overlay" :data-state="isAnimatedIn ? 'open' : undefined"
      :style="{ zIndex: zIndex }"
      @click="handleOverlayClick"
      role="presentation"
      v-bind="$attrs"
    >
      <slot />
    </div>
  </Teleport>
</template>

<script lang="ts">
// Module-level count of open overlays for z-index stacking
let activeOverlayCount = 0;
</script>

<script setup lang="ts">
import { ref, watch, onMounted, onUnmounted } from 'vue';

interface Props {
  isOpen: boolean;
  closeOnOverlayClick?: boolean;
  closeOnEsc?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  closeOnOverlayClick: true,
  closeOnEsc: true,
});

const emit = defineEmits<{
  (e: 'close'): void;
}>();

const shouldRender = ref(props.isOpen);
const isAnimatedIn = ref(false);
const zIndex = ref(1000);
let timeoutId: any = null;

watch(() => props.isOpen, (newVal) => {
  clearTimeout(timeoutId);
  if (newVal) {
    activeOverlayCount++;
    zIndex.value = 1000 + activeOverlayCount;
    shouldRender.value = true;
    document.body.style.overflow = 'hidden';
    timeoutId = setTimeout(() => {
      isAnimatedIn.value = true;
    }, 10);
  } else {
    isAnimatedIn.value = false;
    timeoutId = setTimeout(() => {
      shouldRender.value = false;
      if (activeOverlayCount > 0) {
        activeOverlayCount--;
      }
      if (activeOverlayCount === 0) {
        document.body.style.overflow = '';
      }
    }, 200);
  }
}, { immediate: true });

const handleOverlayClick = (e: MouseEvent) => {
  if (props.closeOnOverlayClick && e.target === e.currentTarget) {
    emit('close');
  }
};

const handleKeyDown = (event: KeyboardEvent) => {
  if (event.key === 'Escape' && props.isOpen && props.closeOnEsc) {
    if (zIndex.value === 1000 + activeOverlayCount) {
      emit('close');
    }
  }
};

onMounted(() => {
  window.addEventListener('keydown', handleKeyDown);
});

onUnmounted(() => {
  window.removeEventListener('keydown', handleKeyDown);
  clearTimeout(timeoutId);
  if (props.isOpen) {
    if (activeOverlayCount > 0) {
      activeOverlayCount--;
    }
    if (activeOverlayCount === 0) {
      document.body.style.overflow = '';
    }
  }
});
</script>
