// packages/angular/popover.component.ts
import { Component, input, output, ElementRef, HostListener, inject, effect } from '@angular/core';

type PopoverPlacement = 'top' | 'top-start' | 'top-end' | 'bottom' | 'bottom-start' | 'bottom-end' | 'left' | 'left-start' | 'left-end' | 'right' | 'right-start' | 'right-end';

@Component({
  selector: 'popover',
  standalone: true,
  template: `
    <div class="popover-trigger" #triggerRef>
      <ng-content select="[ctpPopoverTrigger]" />
    </div>
    @if (isOpen()) {
      <div
        #popoverRef
        class="popover" [attr.data-placement]="actualPlacement"
        [style.position]="'fixed'"
        [style.zIndex]="'1100'"
        [style.top.px]="top"
        [style.left.px]="left"
      >
        <div class="popover-arrow"></div>
        <ng-content />
      </div>
    }
  `,
})
export class PopoverComponent {
  placement = input<PopoverPlacement>('bottom');
  offset = input<number>(8);
  open = input<boolean | undefined>(undefined);

  openChange = output<boolean>();

  isOpen = false;
  top = 0;
  left = 0;
  actualPlacement: PopoverPlacement = 'bottom';

  private el = inject(ElementRef);

  constructor() {
    effect(() => {
      const controlled = this.open();
      if (controlled !== undefined) {
        this.isOpen = controlled;
        if (controlled) this.updatePosition();
      }
    });
  }

  toggle(): void {
    this.isOpen = !this.isOpen;
    this.openChange.emit(this.isOpen);
    if (this.isOpen) this.updatePosition();
  }

  openPopover(): void {
    this.isOpen = true;
    this.openChange.emit(true);
    this.updatePosition();
  }

  closePopover(): void {
    this.isOpen = false;
    this.openChange.emit(false);
  }

  @HostListener('document:mousedown', ['$event'])
  onDocumentClick(event: MouseEvent): void {
    if (!this.isOpen) return;
    const target = event.target as Node;
    const nativeEl = this.el.nativeElement as HTMLElement;
    if (!nativeEl.contains(target)) {
      this.closePopover();
    }
  }

  @HostListener('document:keydown.escape')
  onEscape(): void {
    if (this.isOpen) this.closePopover();
  }

  private updatePosition(): void {
    const nativeEl = this.el.nativeElement as HTMLElement;
    const trigger = nativeEl.querySelector('[ctpPopoverTrigger]') as HTMLElement;
    const popover = nativeEl.querySelector('.popover') as HTMLElement;
    if (!trigger || !popover) return;

    const triggerRect = trigger.getBoundingClientRect();
    const popoverRect = popover.getBoundingClientRect();
    const offset = this.offset();

    this.actualPlacement = this.placement();
    this.top = triggerRect.bottom + offset;
    this.left = triggerRect.left;
  }
}

// packages/vue/Popover.vue
<template>
  <div ref="popoverEl" style="display:contents">
    <span class="popover-trigger" ref="triggerEl" @click="toggle">
      <slot name="trigger" />
    </span>
    <Teleport to="body">
      <div
        v-if="isOpen"
        ref="floatingEl"
        class="popover" :data-placement="actualPlacement"
        :style="{ position: 'fixed', top: top + 'px', left: left + 'px', zIndex: 1100 }"
      >
        <div class="popover-arrow" />
        <slot />
      </div>
    </Teleport>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue';

type PopoverPlacement = 'top' | 'top-start' | 'top-end' | 'bottom' | 'bottom-start' | 'bottom-end' | 'left' | 'left-start' | 'left-end' | 'right' | 'right-start' | 'right-end';

interface Props {
  placement?: PopoverPlacement;
  offset?: number;
  open?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  placement: 'bottom',
  offset: 8,
});

const emit = defineEmits<{
  (e: 'update:open', val: boolean): void;
}>();

const isOpen = ref(false);
const top = ref(0);
const left = ref(0);
const actualPlacement = ref<PopoverPlacement>('bottom');
const popoverEl = ref<HTMLElement>();
const triggerEl = ref<HTMLElement>();
const floatingEl = ref<HTMLElement>();

function toggle() {
  isOpen.value = !isOpen.value;
  emit('update:open', isOpen.value);
  if (isOpen.value) updatePosition();
}

function updatePosition() {
  if (!triggerEl.value) return;
  const rect = triggerEl.value.getBoundingClientRect();
  actualPlacement.value = props.placement;
  top.value = rect.bottom + props.offset;
  left.value = rect.left;
}

function onClickOutside(e: MouseEvent) {
  if (!isOpen.value) return;
  const target = e.target as Node;
  if (popoverEl.value && !popoverEl.value.contains(target)) {
    isOpen.value = false;
    emit('update:open', false);
  }
}

function onEscape(e: KeyboardEvent) {
  if (e.key === 'Escape' && isOpen.value) {
    isOpen.value = false;
    emit('update:open', false);
  }
}

onMounted(() => {
  document.addEventListener('mousedown', onClickOutside);
  document.addEventListener('keydown', onEscape);
});
onUnmounted(() => {
  document.removeEventListener('mousedown', onClickOutside);
  document.removeEventListener('keydown', onEscape);
});
</script>
