// test-native/.mocha-web-temp/src/app/mocha-ds/scroll-area.component.ts
import { Component, input, ViewChild, ElementRef, HostListener, signal, computed } from '@angular/core';

@Component({
  selector: 'scroll-area',
  standalone: true,
  template: `
    <div class="scroll-area" [style.height]="height()">
      <div #viewport class="scroll-area-viewport" (scroll)="updateThumbs()">
        <ng-content />
      </div>
      @if (showVertical()) {
        <div class="scroll-area-scrollbar" data-orientation="vertical" [style.opacity]="isDraggingV ? 1 : 0.6">
          <div
            class="scroll-area-thumb"
            [style.height.px]="thumbHeight()"
            [style.transform]="'translateY(' + thumbTop() + 'px)'"
            (mousedown)="startDragV($event)"
          ></div>
        </div>
      }
      @if (showHorizontal()) {
        <div class="scroll-area-scrollbar" data-orientation="horizontal" [style.opacity]="isDraggingH ? 1 : 0.6">
          <div
            class="scroll-area-thumb"
            [style.width.px]="thumbWidth()"
            [style.transform]="'translateX(' + thumbLeft() + 'px)'"
            (mousedown)="startDragH($event)"
          ></div>
        </div>
      }
      @if (showVertical() && showHorizontal()) {
        <div class="scroll-area-corner"></div>
      }
    </div>
  `
})
export class ScrollAreaComponent {
  height = input<string>('100%');

  @ViewChild('viewport') viewportEl!: ElementRef<HTMLDivElement>;

  showVertical = signal(false);
  showHorizontal = signal(false);
  thumbTop = signal(0);
  thumbLeft = signal(0);
  thumbHeight = signal(0);
  thumbWidth = signal(0);
  isDraggingV = false;
  isDraggingH = false;

  updateThumbs(): void {
    const vp = this.viewportEl?.nativeElement;
    if (!vp) return;

    const { scrollTop, scrollLeft, scrollHeight, scrollWidth, clientHeight, clientWidth } = vp;
    this.showVertical.set(scrollHeight > clientHeight);
    this.showHorizontal.set(scrollWidth > clientWidth);

    if (scrollHeight > clientHeight) {
      this.thumbHeight.set((clientHeight / scrollHeight) * clientHeight);
      this.thumbTop.set((scrollTop / scrollHeight) * clientHeight);
    }
    if (scrollWidth > clientWidth) {
      this.thumbWidth.set((clientWidth / scrollWidth) * clientWidth);
      this.thumbLeft.set((scrollLeft / scrollWidth) * clientWidth);
    }
  }

  startDragV(e: MouseEvent): void {
    e.preventDefault();
    this.isDraggingV = true;
    const vp = this.viewportEl.nativeElement;
    const startY = e.clientY;
    const startScrollTop = vp.scrollTop;

    const onMove = (ev: MouseEvent) => {
      const dy = ev.clientY - startY;
      const ratio = dy / (vp.clientHeight - this.thumbHeight());
      vp.scrollTop = startScrollTop + ratio * (vp.scrollHeight - vp.clientHeight);
    };

    const onUp = () => {
      this.isDraggingV = false;
      window.removeEventListener('mousemove', onMove);
      window.removeEventListener('mouseup', onUp);
    };

    window.addEventListener('mousemove', onMove);
    window.addEventListener('mouseup', onUp);
  }

  startDragH(e: MouseEvent): void {
    e.preventDefault();
    this.isDraggingH = true;
    const vp = this.viewportEl.nativeElement;
    const startX = e.clientX;
    const startScrollLeft = vp.scrollLeft;

    const onMove = (ev: MouseEvent) => {
      const dx = ev.clientX - startX;
      const ratio = dx / (vp.clientWidth - this.thumbWidth());
      vp.scrollLeft = startScrollLeft + ratio * (vp.scrollWidth - vp.clientWidth);
    };

    const onUp = () => {
      this.isDraggingH = false;
      window.removeEventListener('mousemove', onMove);
      window.removeEventListener('mouseup', onUp);
    };

    window.addEventListener('mousemove', onMove);
    window.addEventListener('mouseup', onUp);
  }
}

// packages/vue/ScrollArea.vue
<template>
  <div class="scroll-area" :style="{ height }">
    <div ref="viewport" class="scroll-area-viewport" @scroll="updateThumbs">
      <slot />
    </div>
    <div
      v-if="showVertical"
      class="scroll-area-scrollbar" data-orientation="vertical"
      :style="{ opacity: isDraggingV ? 1 : 0.6 }"
    >
      <div
        class="scroll-area-thumb"
        :style="{ height: thumbHeight + 'px', transform: `translateY(${thumbTop}px)` }"
        @mousedown.prevent="startDragV"
      />
    </div>
    <div
      v-if="showHorizontal"
      class="scroll-area-scrollbar" data-orientation="horizontal"
      :style="{ opacity: isDraggingH ? 1 : 0.6 }"
    >
      <div
        class="scroll-area-thumb"
        :style="{ width: thumbWidth + 'px', transform: `translateX(${thumbLeft}px)` }"
        @mousedown.prevent="startDragH"
      />
    </div>
    <div v-if="showVertical && showHorizontal" class="scroll-area-corner" />
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue';

interface Props {
  height?: string;
}

const props = withDefaults(defineProps<Props>(), {
  height: '100%',
});

const viewport = ref<HTMLElement>();
const showVertical = ref(false);
const showHorizontal = ref(false);
const thumbTop = ref(0);
const thumbLeft = ref(0);
const thumbHeight = ref(0);
const thumbWidth = ref(0);
const isDraggingV = ref(false);
const isDraggingH = ref(false);

function updateThumbs() {
  const vp = viewport.value;
  if (!vp) return;

  const { scrollTop, scrollLeft, scrollHeight, scrollWidth, clientHeight, clientWidth } = vp;

  showVertical.value = scrollHeight > clientHeight;
  showHorizontal.value = scrollWidth > clientWidth;

  if (scrollHeight > clientHeight) {
    thumbHeight.value = (clientHeight / scrollHeight) * clientHeight;
    thumbTop.value = (scrollTop / scrollHeight) * clientHeight;
  }
  if (scrollWidth > clientWidth) {
    thumbWidth.value = (clientWidth / scrollWidth) * clientWidth;
    thumbLeft.value = (scrollLeft / scrollWidth) * clientWidth;
  }
}

function startDragV(e: MouseEvent) {
  isDraggingV.value = true;
  const vp = viewport.value!;
  const startY = e.clientY;
  const startScrollTop = vp.scrollTop;

  function onMove(ev: MouseEvent) {
    const dy = ev.clientY - startY;
    const ratio = dy / (vp.clientHeight - thumbHeight.value);
    vp.scrollTop = startScrollTop + ratio * (vp.scrollHeight - vp.clientHeight);
  }

  function onUp() {
    isDraggingV.value = false;
    window.removeEventListener('mousemove', onMove);
    window.removeEventListener('mouseup', onUp);
  }

  window.addEventListener('mousemove', onMove);
  window.addEventListener('mouseup', onUp);
}

function startDragH(e: MouseEvent) {
  isDraggingH.value = true;
  const vp = viewport.value!;
  const startX = e.clientX;
  const startScrollLeft = vp.scrollLeft;

  function onMove(ev: MouseEvent) {
    const dx = ev.clientX - startX;
    const ratio = dx / (vp.clientWidth - thumbWidth.value);
    vp.scrollLeft = startScrollLeft + ratio * (vp.scrollWidth - vp.clientWidth);
  }

  function onUp() {
    isDraggingH.value = false;
    window.removeEventListener('mousemove', onMove);
    window.removeEventListener('mouseup', onUp);
  }

  window.addEventListener('mousemove', onMove);
  window.addEventListener('mouseup', onUp);
}

let ro: ResizeObserver;

onMounted(() => {
  if (viewport.value) {
    ro = new ResizeObserver(updateThumbs);
    ro.observe(viewport.value);
    updateThumbs();
  }
});

onUnmounted(() => {
  ro?.disconnect();
});
</script>
