// packages/angular/slider.component.ts
import { Component, input, computed, model, forwardRef } from '@angular/core';
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';
import { FormControlColor, getFormThemeClass } from './form-types';

@Component({
  selector: 'slider',
  standalone: true,
  template: `
    <div class="slider-container" [attr.data-color]="color()">
      <input
        type="range"
        [min]="min()"
        [max]="max()"
        [value]="value()"
        [disabled]="disabled()"
        class="slider"
        (input)="onSliderInput($event)"
        (blur)="onTouchedCallback()"
      />
      @if (showValue()) {
        <span class="slider-value">{{ value() }}</span>
      }
    </div>
  `,
  providers: [{
    provide: NG_VALUE_ACCESSOR,
    useExisting: forwardRef(() => SliderComponent),
    multi: true,
  }],
})
export class SliderComponent implements ControlValueAccessor {
  value = model<number>(50);
  min = input<number>(0);
  max = input<number>(100);
  color = input<FormControlColor>('mauve');
  showValue = input<boolean>(true);
  disabled = input<boolean>(false);

  private _onChange: (val: any) => void = () => {};
  private _onTouched: () => void = () => {};



  writeValue(val: any): void { this.value.set(Number(val) || 0); }
  registerOnChange(fn: any): void { this._onChange = fn; }
  registerOnTouched(fn: any): void { this._onTouched = fn; }
  setDisabledState(isDisabled: boolean): void {}

  onSliderInput(event: Event): void {
    const val = Number((event.target as HTMLInputElement).value);
    this.value.set(val);
    this._onChange(val);
  }

  onTouchedCallback(): void { this._onTouched(); }
}

// packages/vue/Slider.vue
<template>
  <div class="slider-container" :data-color="color">
    <input
      type="range"
      :min="min"
      :max="max"
      :value="modelValue"
      :disabled="disabled"
      class="slider"
      @input="onInput"
    />
    <span v-if="showValue" class="slider-value">{{ modelValue }}</span>
  </div>
</template>

<script setup lang="ts">


type FormControlColor =
  | 'rosewater' | 'flamingo' | 'pink' | 'mauve' | 'red' | 'maroon'
  | 'peach' | 'yellow' | 'green' | 'teal' | 'sky' | 'sapphire'
  | 'blue' | 'lavender';

interface Props {
  modelValue?: number;
  min?: number;
  max?: number;
  color?: FormControlColor;
  showValue?: boolean;
  disabled?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  modelValue: 50,
  min: 0,
  max: 100,
  color: 'mauve',
  showValue: true,
  disabled: false,
});

const emit = defineEmits<{
  (e: 'update:modelValue', value: number): void;
}>();

const getFormThemeClass = (color: FormControlColor) => `form--${color}`;



function onInput(event: Event) {
  const target = event.target as HTMLInputElement;
  emit('update:modelValue', Number(target.value));
}
</script>
