// packages/angular/tabs/tabs-trigger.component.ts
import { Component, input, computed, inject } from '@angular/core';
import { TabsComponent } from './tabs.component';

@Component({
  selector: 'tabs-trigger',
  standalone: true,
  template: `
    <button
      type="button"
      role="tab"
      [attr.aria-selected]="isSelected()"
      [attr.aria-controls]="'tabpanel-' + value()"
      [id]="'tabtrigger-' + value()"
      [attr.data-value]="value()"
      [attr.tabindex]="isSelected() ? 0 : -1"
      [disabled]="disabled()"
      class="tabs-trigger"
      [attr.data-variant]="parent.variant()"
      [attr.data-size]="parent.size()"
      [attr.data-state]="isSelected() ? 'active' : null"
      (click)="handleClick()"
    >
      <ng-content></ng-content>
    </button>
  `
})
export class TabsTriggerComponent {
  value = input.required<string>();
  disabled = input<boolean>(false);
  routerLink = input<string>('');

  parent = inject(TabsComponent);

  isSelected = computed(() => this.parent.isSelected(this.value()));

  handleClick() {
    if (this.disabled()) return;
    this.parent.selectTab(this.value());
  }
}

// packages/vue/TabsTrigger.vue
<template>
  <button
    type="button"
    role="tab"
    :aria-selected="isSelected"
    :aria-controls="`tabpanel-${value}`"
    :id="`tabtrigger-${value}`"
    :data-value="value"
    :tabindex="isSelected ? 0 : -1"
    :disabled="disabled"
    class="tabs-trigger"
    :data-variant="tabs.variant.value"
    :data-size="tabs.size.value"
    :data-state="isSelected ? 'active' : undefined"
    @click="handleClick"
  >
    <slot />
  </button>
</template>

<script setup lang="ts">
import { computed, inject } from 'vue';
import { useRoute } from 'vue-router';

const props = withDefaults(defineProps<{
  value: string;
  disabled?: boolean;
  to?: string;
}>(), {
  disabled: false,
  to: '',
});

const tabs = inject<any>('tabs');
const route = useRoute();

const isSelected = computed(() => {
  if (tabs.mode.value === 'router' && props.to) {
    return route.path === props.to || route.path.startsWith(props.to);
  }
  return tabs.activeValue.value === props.value;
});

function handleClick() {
  if (props.disabled) return;

  if (tabs.mode.value === 'router' && props.to) {
    tabs.navigateTo(props.to);
  } else {
    tabs.selectTab(props.value);
  }
}
</script>
