// packages/vue/Animate.vue
<template>
  <div ref="containerRef" :class="animClass" :style="animStyle">
    <slot />
  </div>
</template>

<script setup lang="ts">
import { computed, ref, onMounted, onUnmounted } from 'vue';

type AnimationName =
  | 'fade-in' | 'fade-up' | 'fade-down' | 'fade-left' | 'fade-right'
  | 'scale-in' | 'slide-up' | 'slide-down' | 'blur-in' | 'bounce-in'
  | 'spin' | 'pulse';

type AnimationDuration = 'fast' | 'normal' | 'slow' | 'slower' | 'slowest';

type AnimationEasing = 'out' | 'in-out' | 'spring';

interface Props {
  animation?: AnimationName;
  duration?: AnimationDuration;
  delay?: number;
  easing?: AnimationEasing;
  once?: boolean;
  threshold?: number;
}

const props = withDefaults(defineProps<Props>(), {
  animation: 'fade-up',
  duration: 'normal',
  delay: 0,
  easing: 'out',
  once: true,
  threshold: 0.2,
});

const containerRef = ref<HTMLElement | null>(null);
const visible = ref(false);
let observer: IntersectionObserver | null = null;

const animClass = computed(() => {
  const parts = [
    `anim--${props.animation}`,
    props.duration !== 'normal' ? `anim--duration-${props.duration}` : '',
    props.easing !== 'out' ? `anim--ease-${props.easing}` : '',
  ];
  return parts.filter(Boolean).join(' ');
});

const animStyle = computed(() => {
  const style: Record<string, string> = {};
  if (props.delay > 0) style['--ctp-anim-delay'] = `${props.delay}ms`;
  if (!visible.value) style['animationPlayState'] = 'paused';
  return style;
});

onMounted(() => {
  if (!containerRef.value) return;

  const canObserve =
    typeof window !== 'undefined' && 'IntersectionObserver' in window;
  if (!canObserve) {
    visible.value = true;
    return;
  }

  observer = new IntersectionObserver(
    ([entry]) => {
      if (entry.isIntersecting) {
        visible.value = true;
        if (props.once) observer?.unobserve(containerRef.value!);
      } else if (!props.once) {
        visible.value = false;
      }
    },
    { threshold: props.threshold },
  );

  observer.observe(containerRef.value);
});

onUnmounted(() => {
  observer?.disconnect();
});
</script>

// packages/angular/animate.component.ts
import {
  Component,
  input,
  computed,
  ViewChild,
  ElementRef,
  AfterViewInit,
  OnDestroy,
  signal,
} from '@angular/core';

export type AnimationName =
  | 'fade-in' | 'fade-up' | 'fade-down' | 'fade-left' | 'fade-right'
  | 'scale-in' | 'slide-up' | 'slide-down' | 'blur-in' | 'bounce-in'
  | 'spin' | 'pulse';

export type AnimationDuration = 'fast' | 'normal' | 'slow' | 'slower' | 'slowest';

export type AnimationEasing = 'out' | 'in-out' | 'spring';

@Component({
  selector: 'animate',
  standalone: true,
  template: `
    <div #container [class]="animClass()" [style]="animStyle()">
      <ng-content />
    </div>
  `,
})
export class AnimateComponent implements AfterViewInit, OnDestroy {
  animation = input<AnimationName>('fade-up');
  duration = input<AnimationDuration>('normal');
  delay = input<number>(0);
  easing = input<AnimationEasing>('out');
  once = input<boolean>(true);
  threshold = input<number>(0.2);

  @ViewChild('container') containerRef!: ElementRef<HTMLDivElement>;

  private visible = signal(false);
  private observer: IntersectionObserver | null = null;

  get isBrowser(): boolean {
    return typeof document !== 'undefined';
  }

  animClass = computed(() => {
    const parts = [
      `anim--${this.animation()}`,
      this.duration() !== 'normal' ? `anim--duration-${this.duration()}` : '',
      this.easing() !== 'out' ? `anim--ease-${this.easing()}` : '',
    ];
    return parts.filter(Boolean).join(' ');
  });

  animStyle = computed(() => {
    const style: Record<string, string | null> = {};
    if (this.delay() > 0) style['--ctp-anim-delay'] = `${this.delay()}ms`;
    if (!this.visible()) style['animationPlayState'] = 'paused';
    return style;
  });

  ngAfterViewInit(): void {
    this.createObserver();
  }

  ngOnDestroy(): void {
    this.observer?.disconnect();
  }

  private createObserver(): void {
    if (!this.isBrowser || typeof IntersectionObserver === 'undefined') {
      this.visible.set(true);
      return;
    }

    this.observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          this.visible.set(true);
          if (this.once()) this.observer?.unobserve(this.containerRef.nativeElement);
        } else if (!this.once()) {
          this.visible.set(false);
        }
      },
      { threshold: this.threshold() },
    );
    this.observer.observe(this.containerRef.nativeElement);
  }
}
