// packages/vue/DynamicForm.vue
<template>
  <form class="dynamic-form" @submit.prevent="onSubmit">
    <div class="form-grid">
      <div
        v-for="field in schema"
        :key="field.id"
        class="form-group form-col-12"
      >
        <label class="form-group-label">
          {{ field.label }}
          <span v-if="field.required" class="form-group-required-indicator">*</span>
        </label>

        <textarea
          v-if="field.type === 'textarea'"
          class="form-control form-control--md form-control--rounded"
          :placeholder="field.placeholder"
          :value="formValues[field.id]"
          @input="setValue(field.id, ($event.target as HTMLTextAreaElement).value)"
        ></textarea>

        <select
          v-else-if="field.type === 'select'"
          class="form-control form-control--md form-control--rounded"
          :value="formValues[field.id]"
          @change="setValue(field.id, ($event.target as HTMLSelectElement).value)"
        >
          <option value="">Selecione...</option>
          <option v-for="opt in (field.options || [])" :key="opt.value" :value="opt.value">
            {{ opt.label }}
          </option>
        </select>

        <label v-else-if="field.type === 'checkbox'" class="checkbox-row">
          <input
            type="checkbox"
            :checked="formValues[field.id] || false"
            @change="setChecked(field.id, ($event.target as HTMLInputElement).checked)"
          />
          <span class="checkbox-box">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor">
              <polyline points="20 6 9 17 4 12"></polyline>
            </svg>
          </span>
          <span>{{ field.label }}</span>
        </label>

        <input
          v-else
          :type="field.type"
          class="form-control form-control--md form-control--rounded"
          :placeholder="field.placeholder"
          :value="formValues[field.id]"
          @input="setValue(field.id, ($event.target as HTMLInputElement).value)"
        />
      </div>
    </div>
    <div style="margin-top:16px">
      <button
        type="submit"
        class="btn btn--filled btn--mauve btn--md btn--rounded"
      >
        {{ submitText }}
      </button>
    </div>
  </form>
</template>

<script setup lang="ts">
import { reactive } from 'vue';

interface FieldOption {
  label: string;
  value: any;
}

interface FieldSchema {
  id: string;
  label: string;
  type: 'text' | 'number' | 'email' | 'textarea' | 'select' | 'checkbox';
  placeholder?: string;
  required?: boolean;
  defaultValue?: any;
  options?: FieldOption[];
}

interface Props {
  schema: FieldSchema[];
  submitText?: string;
}

const props = withDefaults(defineProps<Props>(), {
  schema: () => [],
  submitText: 'Enviar',
});

const emit = defineEmits<{
  (e: 'submit', values: Record<string, any>): void;
}>();

const formValues = reactive<Record<string, any>>({});

// Initialize form values from schema defaults
for (const field of props.schema) {
  formValues[field.id] = field.defaultValue ?? '';
}

function setValue(id: string, value: any) {
  formValues[id] = value;
}

function setChecked(id: string, checked: boolean) {
  formValues[id] = checked;
}

function onSubmit() {
  emit('submit', { ...formValues });
}
</script>

// packages/angular/dynamic-form.component.ts
import { Component, input, output, signal } from '@angular/core';

export interface FieldSchema {
  id: string;
  label: string;
  type: 'text' | 'number' | 'email' | 'textarea' | 'select' | 'checkbox';
  placeholder?: string;
  required?: boolean;
  defaultValue?: any;
  options?: { label: string; value: any }[];
}

@Component({
  selector: 'dynamic-form',
  standalone: true,
  template: `
    <form [class]="'dynamic-form'" (ngSubmit)="onSubmit()">
      <div class="form-grid">
        @for (field of schema(); track field.id) {
          <div class="form-group" [class.form-col-12]="true">
            <label class="form-group-label">
              {{ field.label }}
              @if (field.required) {
                <span class="form-group-required-indicator">*</span>
              }
            </label>

            @switch (field.type) {
              @case ('textarea') {
                <textarea
                  class="form-control form-control--md form-control--rounded"
                  [placeholder]="field.placeholder || ''"
                  [value]="values()[field.id] || ''"
                  (input)="setValue(field.id, $event)"
                ></textarea>
              }
              @case ('select') {
                <select
                  class="form-control form-control--md form-control--rounded"
                  [value]="values()[field.id] || ''"
                  (change)="setValue(field.id, $event)"
                >
                  <option value="">Selecione...</option>
                  @for (opt of field.options || []; track opt.value) {
                    <option [value]="opt.value">{{ opt.label }}</option>
                  }
                </select>
              }
              @case ('checkbox') {
                <label class="checkbox-row">
                  <input
                    type="checkbox"
                    [checked]="values()[field.id] || false"
                    (change)="setChecked(field.id, $event)"
                  />
                  <span class="checkbox-box">
                    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor">
                      <polyline points="20 6 9 17 4 12"></polyline>
                    </svg>
                  </span>
                  <span>{{ field.label }}</span>
                </label>
              }
              @default {
                <input
                  [type]="field.type"
                  class="form-control form-control--md form-control--rounded"
                  [placeholder]="field.placeholder || ''"
                  [value]="values()[field.id] || ''"
                  (input)="setValue(field.id, $event)"
                />
              }
            }
          </div>
        }
      </div>
      <div style="margin-top:16px">
        <button
          type="submit"
          class="btn btn--filled btn--mauve btn--md btn--rounded"
        >
          {{ submitText() }}
        </button>
      </div>
    </form>
  `
})
export class DynamicFormComponent {
  schema = input<FieldSchema[]>([]);
  submitText = input<string>('Enviar');

  submit = output<Record<string, any>>();

  private formValues = signal<Record<string, any>>({});

  values = computed(() => {
    const init: Record<string, any> = {};
    for (const field of this.schema()) {
      init[field.id] = this.formValues()[field.id] ?? field.defaultValue ?? '';
    }
    return init;
  });

  setValue(id: string, event: Event) {
    const target = event.target as HTMLInputElement;
    this.formValues.update(v => ({ ...v, [id]: target.value }));
  }

  setChecked(id: string, event: Event) {
    const target = event.target as HTMLInputElement;
    this.formValues.update(v => ({ ...v, [id]: target.checked }));
  }

  onSubmit() {
    this.submit.emit(this.values());
  }
}
