// packages/vue/Skeleton.vue
<template>
  <div v-if="count > 1" class="skeleton-group" :style="{ gap }">
    <div
      v-for="i in count"
      :key="i"
      class="skeleton"
      :data-variant="variant"
      :data-size="size"
      :data-full="width ? undefined : 'true'"
      :data-animated="animated ? undefined : 'false'"
      :style="customStyle"
      aria-hidden="true"
    />
  </div>
  <div v-else
    class="skeleton"
    :data-variant="variant"
    :data-size="size"
    :data-full="width ? undefined : 'true'"
    :data-animated="animated ? undefined : 'false'"
    :style="customStyle"
    aria-hidden="true"
  >
    <slot />
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';

type SkeletonVariant = 'text' | 'circle' | 'rect';
type SkeletonSize = 'sm' | 'md' | 'lg' | 'xl';

interface Props {
  variant?: SkeletonVariant;
  size?: SkeletonSize;
  width?: string;
  height?: string;
  animated?: boolean;
  count?: number;
  gap?: string;
}

const props = withDefaults(defineProps<Props>(), {
  variant: 'text',
  size: 'md',
  animated: true,
  count: 1,
  gap: '8px',
});

const classes = computed(() => {
  return 'skeleton';
});

const customStyle = computed(() => {
  const style: Record<string, string> = {};
  if (props.width) style.width = props.width;
  if (props.height) style.height = props.height;
  return style;
});
</script>

<style scoped>
.skeleton-group {
  display: flex;
  flex-direction: column;
}
</style>

// packages/angular/skeleton.component.ts
import { Component, input } from '@angular/core';

type SkeletonVariant = 'text' | 'circle' | 'rect';
type SkeletonSize = 'sm' | 'md' | 'lg' | 'xl';

@Component({
  selector: 'skeleton',
  standalone: true,
  template: `
    @if (count() > 1) {
      <div class="skeleton-group" [style.gap]="gap()">
        @for (item of items; track item) {
          <div
            class="skeleton"
            [attr.data-variant]="variant()"
            [attr.data-size]="size()"
            [attr.data-full]="width() ? null : 'true'"
            [attr.data-animated]="animated() ? null : 'false'"
            [style]="customStyle"
          ></div>
        }
      </div>
    } @else {
      <div
        class="skeleton"
        [attr.data-variant]="variant()"
        [attr.data-size]="size()"
        [attr.data-full]="width() ? null : 'true'"
        [attr.data-animated]="animated() ? null : 'false'"
        [style]="customStyle"
      ></div>
    }
    <ng-content />
  `,
  styles: [`
    .skeleton-group {
      display: flex;
      flex-direction: column;
    }
  `]
})
export class SkeletonComponent {
  variant = input<SkeletonVariant>('text');
  size = input<SkeletonSize>('md');
  width = input<string>('');
  height = input<string>('');
  animated = input<boolean>(true);
  count = input<number>(1);
  gap = input<string>('8px');

  get items(): number[] {
    return Array.from({ length: this.count() }, (_, i) => i);
  }

  get classes(): string {
    return 'skeleton';
  }

  get customStyle(): Record<string, string> {
    const style: Record<string, string> = {};
    if (this.width()) style['width'] = this.width();
    if (this.height()) style['height'] = this.height();
    return style;
  }
}
